export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    column: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "Без статуса",
  },
  {
    id: 3,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    column: "Без статуса",
  },
  {
    id: 4,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    column: "Без статуса",
  },
  {
    id: 5,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "Без статуса",
  },
  {
    id: 6,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "Нужно сделать",
  },
  {
    id: 7,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "В рвботе",
  },
  {
    id: 8,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    column: "В рвботе",
  },
  {
    id: 9,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    column: "В рвботе",
  },
  {
    id: 10,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "Тестирование",
  },
  {
    id: 11,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    column: "Готово",
  },
];
